# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
