# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 10:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20171017_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
