# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171018_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='bio',
        ),
    ]
